#%RAML 0.8
---
title: API мобильного приложения Едадил
version: 3
protocols: [ HTTPS ]
baseUri: https://edadeal.ru/api/v{version}

documentation:
    - title: Статус документа
      content: |
            Данный документ находится в процессе разработки. Условия работы, используемые протоколы, методы и форматы данных могут быть изменены.

    - title: Совместимость
      content: |
            Гарантируется полная обратная совместимость в рамках версии 3.

    - title: Отличия от предыдущих версий
      content: |
            * Поля с датами имеют формат Unix timestamp UTC
            * Отказ от модификаторов получаемых данных (modes: fetch, expanded и т.д.)
            * При возникновении ошибки возвращается только HTTP код состояния
            * Отказ от поддержки авторизационных токенов приложений
            * Отказ от внутренних автоинкрементируемых полей _id_

traits:
    - tokenized:
        headers:
            Distinct-Id:
                displayName: Уникальный идентификатор устройства
                required: true
                type: string
                example: 0dcb0fb2-4b2f-41e4-8f00-6668d83cb765
                pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$

    - authenticated:
        headers:
            User-Id:
                displayName: Уникальный идентификатор пользователя
                description: |
                    Обязательно указывается для аутентифицированного пользователя
                type: string
                example: 4b1ebbd1-c87c-40e9-84d9-acd70bbdcb12
                pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$

